@startuml
title Cloud Architecture - Putting It Together: A Reference Implementation
class Service {
  +process(req)
  +evaluate(sample)
}
class Repository {
  +get(id)
  +put(e)
}
Service --> Repository
@enduml