@startuml
title Network - Defending Against Prompt Injection
package "Defending Against Prompt Injection Platform" {
  component "Defending Against Promp…" as C0
  component "Retrieval-Augmented Pro…" as C1
  component "Zero-, One- and Few-Sho…" as C2
  component "Decoding Parameters and…" as C3
  component "Prompt Templates and Co…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml