graph LR
  D(("Generative AI"))
  D --- C0[Generative Modelling …]
  D --- C1[Large Language Models…]
  D --- C2[Diffusion Models for …]
  D --- C3[Multimodal Generation]
  D --- C4[Grounding with Enterp…]
  C0 --- C1
  C1 --- C2