@startuml
title Infrastructure - Evaluation of Generative Systems
package "Generative AI Platform" {
  component "Generative Modelling Fo…" as C0
  component "Large Language Models a…" as C1
  component "Diffusion Models for Im…" as C2
  component "Multimodal Generation" as C3
  component "Grounding with Enterpri…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml