@startuml
title Infrastructure - Evaluation of Generative Systems
package "Evaluation of Generative Systems Platform" {
  component "Evaluation of Generativ…" as C0
  component "Safety, Guardrails and …" as C1
  component "Productionising Generat…" as C2
  component "Large Language Models a…" as C3
  component "Controllability and Str…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml