graph LR
  D(("Putting It Together…"))
  D --- C0[Putting It Together: …]
  D --- C1[The GenAI Reference A…]
  D --- C2[Grounding with Enterp…]
  D --- C3[Diffusion Models for …]
  D --- C4[Evaluation of Generat…]
  C0 --- C1
  C1 --- C2