@startuml
title Infrastructure - Safety, Guardrails and Content Moderation
package "Safety, Guardrails and Content Moderation Platform" {
  component "Safety, Guardrails and …" as C0
  component "Evaluation of Generativ…" as C1
  component "Diffusion Models for Im…" as C2
  component "Productionising Generat…" as C3
  component "Synthetic Data Generati…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml