graph LR
  D(("Grounding with Ente…"))
  D --- C0[Grounding with Enterp…]
  D --- C1[Generative Modelling …]
  D --- C2[Governance and Intell…]
  D --- C3[Diffusion Models for …]
  D --- C4[Synthetic Data Genera…]
  C0 --- C1
  C1 --- C2