@startuml
title Component - Handling Tables, Images and Code
package "Handling Tables, Images and Code Platform" {
  component "Handling Tables, Images…" as C0
  component "Document Ingestion and …" as C1
  component "Re-ranking and Context …" as C2
  component "Advanced RAG Patterns" as C3
  component "The End-to-End RAG Refe…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml