@startuml
title Network - Evaluation and Quality Assurance
package "Evaluation and Quality Assurance Platform" {
  component "Evaluation and Quality …" as C0
  component "Optimisation and Gradie…" as C1
  component "The Modern AI Stack" as C2
  component "Scaling Laws and Comput…" as C3
  component "The AI/ML Landscape and…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml