graph LR
  D(("Neural Networks and…"))
  D --- C0[Neural Networks and B…]
  D --- C1[Data Engineering and …]
  D --- C2[Representation Learni…]
  D --- C3[Regularisation and Ge…]
  D --- C4[Responsible and Trust…]
  C0 --- C1
  C1 --- C2