"""Render a :class:`Book` to a complete, professionally structured Markdown
document containing all 21 required front/back-matter sections plus the full
chapter body, diagrams, code, tables and assessments.

``diagram_mode`` controls how diagrams are embedded:

* ``"source"`` (default) — emit the editable diagram source (Mermaid fences,
  raw SVG, PlantUML/Draw.io blocks). Best for the ``.md`` download.
* ``"svg"`` — embed the self-contained rendered SVG inline so diagrams are
  always visible with no external renderer. Used for the HTML export.
"""
from __future__ import annotations

from ..models import Book, Diagram


def _diagram_md(d: Diagram, fig_no: int, mode: str = "source") -> str:
    cap = f"**Figure {fig_no}. {d.title}** ({d.fmt}). {d.caption}"
    if mode == "svg":
        svg = d.render_svg or (d.source if d.fmt == "svg" else "")
        if svg:
            return f'<div class="diagram-svg">\n\n{svg}\n\n</div>\n\n{cap}\n'
    if d.fmt == "mermaid":
        return f"```mermaid\n{d.source}\n```\n\n{cap}\n"
    if d.fmt == "svg":
        return f'<div class="diagram-svg">\n\n{d.source}\n\n</div>\n\n{cap}\n'
    lang = {"plantuml": "plantuml", "drawio": "xml"}.get(d.fmt, "text")
    return (
        f"```{lang}\n{d.source}\n```\n\n"
        f"_Source diagram ({d.fmt}); render with the appropriate tool._\n\n{cap}\n"
    )


def render_markdown(book: Book, *, diagram_mode: str = "source") -> str:
    out: list[str] = []
    A = out.append
    fig_no = 0
    tables: list[tuple[int, str]] = []

    # 1. Cover Page
    A(f"# {book.title}\n")
    A(f"## {book.subtitle}\n")
    A(f"**{book.category}** &nbsp;|&nbsp; **Level:** {book.level} &nbsp;|&nbsp; "
      f"**{book.edition}**\n")
    A(f"**Authors:** {', '.join(book.authors)}\n")
    A(f"**Publisher:** AI-University Press &nbsp;|&nbsp; **ISBN:** {book.isbn} "
      f"&nbsp;|&nbsp; **Version:** {book.version} &nbsp;|&nbsp; **{book.published}**\n")
    A("\n---\n")

    # 2. Copyright Page
    A("## Copyright\n")
    A(f"Copyright \u00a9 {book.published} AI-University Press. All rights reserved.\n")
    A("This work is published as part of the AI-University Enterprise AI Knowledge "
      "Series. It is generated by an automated publishing engine and curated for "
      "professional and educational use. No part of this publication may be reproduced "
      "for commercial resale without attribution to AI-University Press.\n")
    A(f"First published {book.published}. {book.edition}. Document version "
      f"{book.version}.\n")
    A("\n---\n")

    # 3. Table of Contents
    A("## Table of Contents\n")
    A("**Front Matter**\n")
    for s in ["Executive Summary", "Learning Objectives", "Industry Context",
              "Business Perspective", "Technical Perspective", "Architecture Perspective",
              "Governance Perspective", "Security Perspective"]:
        A(f"- {s}")
    A("\n**Chapters**\n")
    for ch in book.chapters:
        A(f"{ch.number}. {ch.title}")
    A("\n**Back Matter**\n")
    for s in ["Hands-On Labs", "Case Studies", "Interview Questions",
              "Certification Questions", "Assessment Exercises", "References",
              "Glossary", "Index"]:
        A(f"- {s}")
    A("\n---\n")

    tbl_no = 1
    A(f"**Table {tbl_no}. Chapter overview and estimated length**\n")
    A("| # | Chapter | Est. pages | Diagrams | Code | Questions |")
    A("|---|---------|-----------:|---------:|-----:|----------:|")
    for ch in book.chapters:
        A(f"| {ch.number} | {ch.title} | {ch.estimated_pages} | "
          f"{len(ch.diagrams)} | {len(ch.code_samples)} | {len(ch.questions)} |")
    tables.append((tbl_no, "Chapter overview and estimated length"))
    A("\n---\n")

    figures_marker = len(out)
    A("§§FIGURES§§")
    A("\n---\n")
    tables_marker = len(out)
    A("§§TABLES§§")
    A("\n---\n")

    fm = book.front_matter
    A("## Executive Summary\n"); A(fm.executive_summary + "\n")
    A("## Learning Objectives\n")
    A("After completing this book, the reader will be able to:\n")
    for o in fm.learning_objectives:
        A(f"- {o}")
    A("")
    A("## Industry Context\n"); A(fm.industry_context + "\n")
    A("## Business Perspective\n"); A(fm.business_perspective + "\n")
    A("## Technical Perspective\n"); A(fm.technical_perspective + "\n")
    A("## Architecture Perspective\n"); A(fm.architecture_perspective + "\n")
    A("## Governance Perspective\n"); A(fm.governance_perspective + "\n")
    A("## Security Perspective\n"); A(fm.security_perspective + "\n")
    A("\n---\n")

    figures: list[tuple[int, str]] = []
    for ch in book.chapters:
        A(f"\n# Chapter {ch.number}. {ch.title}\n")
        A(f"_{ch.summary}_\n")
        for sec in ch.sections:
            A(f"## {sec.heading}\n")
            A(sec.body + "\n")
            if sec.heading.startswith("Architecture"):
                for d in ch.diagrams:
                    fig_no += 1
                    figures.append((fig_no, d.title))
                    A(_diagram_md(d, fig_no, diagram_mode))
        for cs in ch.code_samples:
            A(f"### Listing: {cs.title}\n")
            A(f"```{cs.language}\n{cs.code}\n```\n")
        A("## Review Questions\n")
        for i, q in enumerate(ch.questions, 1):
            if q.kind == "interview":
                A(f"{i}. *(Discussion)* {q.question}")
                A(f"   - **Model answer:** {q.explanation}")
            else:
                A(f"{i}. {q.question}")
                for j, opt in enumerate(q.options):
                    A(f"   - {chr(ord('A') + j)}. {opt}")
                A(f"   - **Answer: {chr(ord('A') + q.answer_index)}.** {q.explanation}")
        A("\n---\n")

    bm = book.back_matter
    A("\n# Hands-On Labs\n")
    for lab in bm.labs:
        A(f"## {lab['title']}\n"); A(lab["body"] + "\n")
    A("\n# Case Studies\n")
    for cs in bm.case_studies:
        A(f"## {cs['title']}\n"); A(cs["body"] + "\n")

    interview = [q for ch in book.chapters for q in ch.questions if q.kind == "interview"]
    cert = [q for ch in book.chapters for q in ch.questions if q.kind == "certification"]
    assess = [q for ch in book.chapters for q in ch.questions if q.kind == "assessment"]

    A("\n# Interview Questions\n")
    A("A consolidated bank of discussion-style interview questions drawn from across "
      "the book, suitable for preparation and technical screening.\n")
    for i, q in enumerate(interview, 1):
        A(f"{i}. {q.question}"); A(f"   - **Guidance:** {q.explanation}")

    A("\n# Certification Questions\n")
    A("Certification-style multiple-choice questions covering best practices and "
      "common pitfalls.\n")
    for i, q in enumerate(cert, 1):
        A(f"{i}. {q.question}")
        for j, opt in enumerate(q.options):
            A(f"   - {chr(ord('A')+j)}. {opt}")
        A(f"   - **Answer: {chr(ord('A')+q.answer_index)}.** {q.explanation}")

    A("\n# Assessment Exercises\n")
    A("Assessment items to verify conceptual understanding.\n")
    for i, q in enumerate(assess, 1):
        A(f"{i}. {q.question}")
        for j, opt in enumerate(q.options):
            A(f"   - {chr(ord('A')+j)}. {opt}")
        A(f"   - **Answer: {chr(ord('A')+q.answer_index)}.** {q.explanation}")

    A("\n# References\n")
    for i, r in enumerate(bm.references, 1):
        A(f"{i}. {r}")

    A("\n# Glossary\n")
    tbl2 = 2
    A(f"**Table {tbl2}. Glossary of key terms**\n")
    A("| Term | Definition |")
    A("|------|------------|")
    for g in bm.glossary:
        A(f"| {g['term']} | {g['definition']} |")
    tables.append((tbl2, "Glossary of key terms"))

    A("\n# Index\n")
    A(", ".join(bm.index_terms) + "\n")

    lof = ["## List of Figures\n"]
    for n, title in figures:
        lof.append(f"- Figure {n}. {title}")
    out[figures_marker] = "\n".join(lof)
    lot = ["## List of Tables\n"]
    for n, cap in tables:
        lot.append(f"- Table {n}. {cap}")
    out[tables_marker] = "\n".join(lot)

    return "\n".join(out) + "\n"
