@startuml
title Network - Certification Preparation and Review
package "Certification Preparation and Review Platform" {
  component "Certification Preparati…" as C0
  component "Governance and Lineage" as C1
  component "Graphs for Grounding LL…" as C2
  component "Reasoning and Inference" as C3
  component "Entity Extraction and L…" as C4
}
database "Storage" as DB
C0 --> DB
C1 --> DB
C2 --> DB
C3 --> DB
C4 --> DB
@enduml